from abc import ABC, abstractmethod
from typing import Any, Dict, List, Optional

class IEventStreamService(ABC):
    """Interface for real-time event streaming using Redis Streams or similar."""
    
    @abstractmethod
    async def publish_event(self, stream_id: str, event_data: Dict[str, Any]) -> str:
        """
        Publishes an event to the stream.
        
        Args:
            stream_id: The identifier for the stream (e.g. job_id).
            event_data: The payload to publish.
            
        Returns:
            The message ID generated by the streaming system.
        """
        pass

    @abstractmethod
    async def read_stream(
        self, 
        stream_id: str, 
        last_id: str = "0", 
        timeout_ms: int = 5000
    ) -> List[Dict[str, Any]]:
        """
        Reads new events from the stream.
        
        Args:
            stream_id: The identifier for the stream.
            last_id: The ID of the last processed message.
            timeout_ms: How long to block waiting for new messages.
            
        Returns:
            A list of events (each containing 'id' and 'data').
        """
        pass

    @abstractmethod
    async def delete_stream(self, stream_id: str) -> None:
        """Deletes the stream and its associated data."""
        pass
        
    @abstractmethod
    async def set_expiration(self, stream_id: str, seconds: int) -> None:
        """Sets a TTL for the stream."""
        pass
